### PR TITLE
Add livereload support

### PR DESCRIPTION
**Pull request by sakamies**
Making a styleguide using Stylemark at work and wanted live reload. What do you think?

### CODE REVIEW

**Comment by sakamies** [comment]
I haven't gotten quite familiar with code testing yet, does this need a test case?

**Comment by mpetrovich** [comment]
Thanks for your contribution! Livereload is a great idea.

> I haven't gotten quite familiar with code testing yet, does this need a test case?

Not for the functionality you're adding. Your PR passes the existing unit tests (see the green check marks next to each commit), so you're all set.

However, it looks like your code is out-of-date from the master branch. Could you rebase/merge the latest changes?

**Comment by mpetrovich** [comment]
Actually, the changes are small enough that I can integrate them manually, so don't worry about fixing this PR. I'll let you know once they're in!

**Comment by mpetrovich** [comment]
I'm having trouble getting livereload to work out of the box. It's not ideal that it requires a script to be added _and_ a custom browser extension to be installed.

I think [Browsersync](https://www.browsersync.io/) might be a better tool—it's a trivial npm install and requires no additional code changes or browser extensions.

```sh
npm install -g browser-sync
npm install -g stylemark
stylemark -i path/to/my/source -o path/to/style/guide
browser-sync start -s -f path/to/style/guide
```
…will open a browser window that will automatically reload whenever `path/to/style/guide` changes.

With those changes, every time you update the style guide via the `stylemark -i …` command, it will automatically refresh your browser.

**Comment by mpetrovich** [comment]
Stylemark v0.4.0 now has auto-watching and auto-reloading built-in, so this PR is no longer necessary. See the [command-line docs](https://github.com/nextbigsoundinc/stylemark#on-the-command-line).

To automatically launch a browser that will auto-reload whenever you make changes to your source code, it's as simple as adding:
```sh
bin/stylemark -i path/to/source/code -o path/to/style/guide -w -b
```

**Comment by mpetrovich** [comment]
@sakamies I originally mistook some of your CSS & HTML changes for merge differences, but those were actually legitimate! I've applied those same fixes which are now available as of v0.4.2. Thanks again for your contribution, and sorry about the mixup!

**Comment by sakamies** [comment]
Wow, sounds excellent, thank you!

**Pull request closed without merging**
